<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SkylinkMonitoreo-e39dd210-c6a7-4d21-bdf6-10b29acde3d2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Skysense-business\Skysense-business.csproj" />
    <ProjectReference Include="..\Skysense-Data\Skysense-Data.csproj" />
    <ProjectReference Include="..\Skysense-models\Skysense-models.csproj" />
    <ProjectReference Include="..\Skysense-persistencia\Skysense-persistencia.csproj" />
  </ItemGroup>
</Project>
