// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class BessAlerta
{
    public int IdAlerta { get; set; }

    public int IdBess { get; set; }

    public byte IdNivelAlerta { get; set; }

    public string Titulo { get; set; }

    public string Texto { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public byte IdEstado { get; set; }

    public virtual Bess IdBessNavigation { get; set; }
}