// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Bess
{
    public int IdInstalacion { get; set; }

    public string UrlConexionBess { get; set; }

    public bool Monitorear { get; set; }

    public byte? Estatus { get; set; }

    public DateTime? UltimaActualizacionEstatus { get; set; }

    public string MensajeEstatus { get; set; }

    public string CadenaConexion { get; set; }

    public virtual ICollection<BessAlerta> BessAlerta { get; set; } = new List<BessAlerta>();

    public virtual Instalacione IdInstalacionNavigation { get; set; }

    public virtual ICollection<TagsBess> TagsBesses { get; set; } = new List<TagsBess>();
}