// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class CatalogoOpcione
{
    public int IdCatalogo { get; set; }

    public int IdOpcion { get; set; }

    public string NombreOpcion { get; set; }

    public string InfoAdicional { get; set; }

    public bool Disponible { get; set; }

    public virtual CatalogoMaestro IdCatalogoNavigation { get; set; }
}