// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public byte IndicadorEstado { get; set; }

    public bool? EsEspecial { get; set; }

    public string Rfc { get; set; }

    public string Contacto { get; set; }

    public virtual ICollection<Instalacione> Instalaciones { get; set; } = new List<Instalacione>();
}