// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class DatosInversoresAjustado
{
    public int IdAjuste { get; set; }

    public int? IdInstalacion { get; set; }

    public string IdentificadorInversor { get; set; }

    public string IdUsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public decimal? ValorOriginal { get; set; }

    public decimal? ValorNuevo { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }

    public virtual AspNetUser IdUsuarioModificacionNavigation { get; set; }
}