// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class DiasFestivo
{
    public int IdDiaFestivo { get; set; }

    public DateOnly FechaFestiva { get; set; }
}