// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class DobleVerificacion
{
    public int IdVerificacion { get; set; }

    public string CodigoVerificacion { get; set; }

    public DateTime FechaSolicitud { get; set; }

    public DateTime Expiracion { get; set; }

    public byte Estatus { get; set; }

    public byte? IntentosRestantes { get; set; }

    public int IdUsuarioRelacionado { get; set; }

    public byte IdProceso { get; set; }

    public virtual User IdUsuarioRelacionadoNavigation { get; set; }
}