// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Documento
{
    public int IdDocumento { get; set; }

    public int? IdInstalacion { get; set; }

    public byte TipoDocumento { get; set; }

    public string NombreDocumento { get; set; }

    public string TipoArchivo { get; set; }

    public int Peso { get; set; }

    public string RutaRelativa { get; set; }

    public DateTime FechaModificacion { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }

    public virtual ICollection<RecibosMensuale> RecibosMensuales { get; set; } = new List<RecibosMensuale>();

    public virtual ICollection<ReportesMensuale> ReportesMensuales { get; set; } = new List<ReportesMensuale>();
}