// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Skysense_persistencia.Entidades
{
    public partial class fObtenKPIInstalacionesAnualMensualResult
    {
        public int IdInstalacion { get; set; }
        public int IdCliente { get; set; }
        public short IdGrupo { get; set; }
        [StringLength(200)]
        public string Nombre { get; set; }
        public short? Anno { get; set; }
        [Column("GeneracionReal", TypeName = "decimal(38,3)")]
        public decimal? GeneracionReal { get; set; }
        [Column("GeneracionGarantizada", TypeName = "decimal(38,12)")]
        public decimal? GeneracionGarantizada { get; set; }
        [Column("Porcentaje", TypeName = "decimal(38,6)")]
        public decimal? Porcentaje { get; set; }
    }
}
