// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Skysense_persistencia.Entidades
{
    public partial class fObtenGeneracionDiariaInversorResult
    {
        public int IdInversorAPI { get; set; }
        public DateTime FechaValor { get; set; }
        [Column("Valor", TypeName = "decimal(18,3)")]
        public decimal Valor { get; set; }
    }
}
