// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Grupo
{
    public short IdGrupo { get; set; }

    public string Nombre { get; set; }

    public bool? Disponible { get; set; }

    public virtual ICollection<Instalacione> Instalaciones { get; set; } = new List<Instalacione>();
}