// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Instalacione
{
    public int IdInstalacion { get; set; }

    public int IdCliente { get; set; }

    public int? IdPlataforma { get; set; }

    public int? IdCatalogoEstatus { get; set; }

    public int? IdCatalogoTarifa { get; set; }

    public string Nombre { get; set; }

    public string CodigoProyecto { get; set; }

    public string Longitud { get; set; }

    public string Latitud { get; set; }

    public string Estado { get; set; }

    public string Ubicacion { get; set; }

    public DateOnly? GarantiaInicio { get; set; }

    public DateOnly? GarantiaFin { get; set; }

    public int? IdCatalogoGarantiaEstatus { get; set; }

    public DateOnly? InicioOperaciones { get; set; }

    public decimal? PorcentajeDesgastePaneles { get; set; }

    public string IdInstalacionApi { get; set; }

    public string Rpu { get; set; }

    public short? IdGrupo { get; set; }

    public int? AnioInstalacion { get; set; }

    public string ContactoNombre { get; set; }

    public string ContactoTelefono { get; set; }

    public string ContactoEmail { get; set; }

    public decimal? PotenciaInstalada { get; set; }

    public bool? EsFinanciado { get; set; }

    public DateTime? FechaUltimaActualizacionDaemonApi { get; set; }

    public short? Zona { get; set; }

    public int TipoProyecto { get; set; }

    public virtual Bess Bess { get; set; }

    public virtual ICollection<DatosInversoresAjustado> DatosInversoresAjustados { get; set; } = new List<DatosInversoresAjustado>();

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Grupo IdGrupoNavigation { get; set; }

    public virtual ICollection<InstalacionApigeneracionMensual> InstalacionApigeneracionMensuals { get; set; } = new List<InstalacionApigeneracionMensual>();

    public virtual ICollection<InversorApiencabezado> InversorApiencabezados { get; set; } = new List<InversorApiencabezado>();

    public virtual ICollection<Inversor> Inversors { get; set; } = new List<Inversor>();

    public virtual ICollection<Panele> Paneles { get; set; } = new List<Panele>();

    public virtual ICollection<RecibosMensuale> RecibosMensuales { get; set; } = new List<RecibosMensuale>();

    public virtual ReporteAutomaticoConfig ReporteAutomaticoConfig { get; set; }

    public virtual ICollection<ReportesMensuale> ReportesMensuales { get; set; } = new List<ReportesMensuale>();
}