// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class InversorApiencabezado
{
    public int IdInversorApi { get; set; }

    public int? IdInstalacion { get; set; }

    public int? IdInversor { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public DateTime FechaUltimaActualizacion { get; set; }

    public string IdApi { get; set; }

    public string NumeroSerie { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }

    public virtual Inversor IdInversorNavigation { get; set; }

    public virtual ICollection<InversorApigeneracion> InversorApigeneracions { get; set; } = new List<InversorApigeneracion>();
}