// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Inversor
{
    public int IdInversor { get; set; }

    public int IdInstalacion { get; set; }

    public byte IdEstadoInversor { get; set; }

    public string NumeroSerie { get; set; }

    public string Modelo { get; set; }

    public string Marca { get; set; }

    public decimal Potencia { get; set; }

    public decimal DegradacionAnual { get; set; }

    public string ProveedorSuministrador { get; set; }

    public string ProveedorSuministradorRfc { get; set; }

    public string ProveedorIntermediario { get; set; }

    public string ProveedorIntermediarioRfc { get; set; }

    public bool EsInicial { get; set; }

    public bool Danado { get; set; }

    public string NumeroSerieReemplazo { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }

    public virtual ICollection<InversorApiencabezado> InversorApiencabezados { get; set; } = new List<InversorApiencabezado>();
}