// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class InversorApigeneracion
{
    public int IdInversorApi { get; set; }

    public int IdConsecutivo { get; set; }

    public DateTime FechaValor { get; set; }

    public DateTime FechaUltimaActualizacion { get; set; }

    public decimal Valor { get; set; }

    public bool ValorManual { get; set; }

    public virtual InversorApiencabezado IdInversorApiNavigation { get; set; }
}