// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Skysense_persistencia.Entidades;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Skysense_persistencia.Entidades
{
    public partial interface ISkysenseDevContextProcedures
    {
        Task<int> spGeneraBDDMedicionesAsync(int? idInstalacion, OutputParameter<string> vcNuevaBD, OutputParameter<bool?> bError, OutputParameter<string> sMensajeInfo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
