// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class ParametrosSistema
{
    public int IdParametro { get; set; }

    public string NombreParametro { get; set; }

    public string Descripcion { get; set; }

    public string Valor { get; set; }

    public string TipoDato { get; set; }
}