// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class ParametrosBess
{
    public short IdParametro { get; set; }

    public string Medicion { get; set; }

    public string Unidad { get; set; }

    public string Observaciones { get; set; }

    public bool SoloLectura { get; set; }

    public bool EsBooleano { get; set; }

    public bool EsGraficable { get; set; }

    public virtual ICollection<TagsBess> TagsBesses { get; set; } = new List<TagsBess>();
}