// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class RecibosMensuale
{
    public int IdRecibo { get; set; }

    public int IdInstalacion { get; set; }

    public DateOnly MesRecibo { get; set; }

    public int? IdDocumento { get; set; }

    public decimal? KWhBase { get; set; }

    public decimal? KWhIntermedia { get; set; }

    public decimal? KWhPunta { get; set; }

    public decimal? KWbase { get; set; }

    public decimal? KWintermedia { get; set; }

    public decimal? KWpunta { get; set; }

    public decimal? ReactivosKvArh { get; set; }

    public decimal? Pago { get; set; }

    public virtual Documento IdDocumentoNavigation { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }
}