// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class ReporteAutomaticoConfig
{
    public int IdInstalacion { get; set; }

    public string NombreEnRecibo { get; set; }

    public decimal? PorcentajeDap { get; set; }

    public decimal? UmbralFp { get; set; }

    public decimal? FpDefault { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }

    public bool? BajaTension2 { get; set; }

}