// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class ReportesMensuale
{
    public int IdReporte { get; set; }

    public int IdInstalacion { get; set; }

    public DateOnly MesReporte { get; set; }

    public int? IdDocumento { get; set; }

    public decimal? PanelesGeneracion { get; set; }

    public decimal? AhorroAcumulado { get; set; }

    public decimal? AhorroAmbiental { get; set; }

    public decimal? ConsumoCfe { get; set; }

    public virtual Documento IdDocumentoNavigation { get; set; }

    public virtual Instalacione IdInstalacionNavigation { get; set; }
}