// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class Role
{
    public byte IdRol { get; set; }

    public string Nombre { get; set; }

    public bool Disponible { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}