// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Skysense_persistencia.Entidades;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Skysense_persistencia.Entidades
{
    public partial class SkysenseDevContext
    {
        private ISkysenseDevContextProcedures _procedures;

        public virtual ISkysenseDevContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SkysenseDevContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISkysenseDevContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class SkysenseDevContextProcedures : ISkysenseDevContextProcedures
    {
        private readonly SkysenseDevContext _context;

        public SkysenseDevContextProcedures(SkysenseDevContext context)
        {
            _context = context;
        }

        public virtual async Task<int> spGeneraBDDMedicionesAsync(int? idInstalacion, OutputParameter<string> vcNuevaBD, OutputParameter<bool?> bError, OutputParameter<string> sMensajeInfo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parametervcNuevaBD = new SqlParameter
            {
                ParameterName = "vcNuevaBD",
                Size = 100,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = vcNuevaBD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterbError = new SqlParameter
            {
                ParameterName = "bError",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = bError?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Bit,
            };
            var parametersMensajeInfo = new SqlParameter
            {
                ParameterName = "sMensajeInfo",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = sMensajeInfo?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idInstalacion",
                    Value = idInstalacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parametervcNuevaBD,
                parameterbError,
                parametersMensajeInfo,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[spGeneraBDDMediciones] @idInstalacion = @idInstalacion, @vcNuevaBD = @vcNuevaBD OUTPUT, @bError = @bError OUTPUT, @sMensajeInfo = @sMensajeInfo OUTPUT", sqlParameters, cancellationToken);

            vcNuevaBD?.SetValue(parametervcNuevaBD.Value);
            bError?.SetValue(parameterbError.Value);
            sMensajeInfo?.SetValue(parametersMensajeInfo.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
