// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Skysense_persistencia.Entidades;

public partial class SkysenseDevContext : DbContext
{
    public SkysenseDevContext(DbContextOptions<SkysenseDevContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<Bess> Besses { get; set; }

    public virtual DbSet<BessAlerta> BessAlertas { get; set; }

    public virtual DbSet<CatalogoMaestro> CatalogoMaestros { get; set; }

    public virtual DbSet<CatalogoOpcione> CatalogoOpciones { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<DatosInversoresAjustado> DatosInversoresAjustados { get; set; }

    public virtual DbSet<DiasFestivo> DiasFestivos { get; set; }

    public virtual DbSet<DobleVerificacion> DobleVerificacions { get; set; }

    public virtual DbSet<Documento> Documentos { get; set; }

    public virtual DbSet<Grupo> Grupos { get; set; }

    public virtual DbSet<InstalacionApigeneracionMensual> InstalacionApigeneracionMensuals { get; set; }

    public virtual DbSet<Instalacione> Instalaciones { get; set; }

    public virtual DbSet<Inversor> Inversors { get; set; }

    public virtual DbSet<InversorApiencabezado> InversorApiencabezados { get; set; }

    public virtual DbSet<InversorApigeneracion> InversorApigeneracions { get; set; }

    public virtual DbSet<Panele> Paneles { get; set; }

    public virtual DbSet<ParametrosBess> ParametrosBesses { get; set; }

    public virtual DbSet<ParametrosSistema> ParametrosSistemas { get; set; }

    public virtual DbSet<Plataforma> Plataformas { get; set; }

    public virtual DbSet<RecibosMensuale> RecibosMensuales { get; set; }

    public virtual DbSet<ReporteAutomaticoConfig> ReporteAutomaticoConfigs { get; set; }

    public virtual DbSet<ReportesMensuale> ReportesMensuales { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<TagsBess> TagsBesses { get; set; }

    public virtual DbSet<TarifasDivisione> TarifasDivisiones { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<Bess>(entity =>
        {
            entity.HasKey(e => e.IdInstalacion).HasName("PK__Bess__03A6C039FC1DB856");

            entity.ToTable("Bess");

            entity.Property(e => e.IdInstalacion).ValueGeneratedNever();
            entity.Property(e => e.CadenaConexion).IsUnicode(false);
            entity.Property(e => e.MensajeEstatus)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.UrlConexionBess)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.IdInstalacionNavigation).WithOne(p => p.Bess)
                .HasForeignKey<Bess>(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bess__IdInstalac__6D6238AF");
        });

        modelBuilder.Entity<BessAlerta>(entity =>
        {
            entity.HasKey(e => e.IdAlerta).HasName("PK__BessAler__D2CDBC4FB3214189");

            entity.Property(e => e.IdBess).HasColumnName("IdBESS");
            entity.Property(e => e.IdNivelAlerta).HasDefaultValue((byte)1);
            entity.Property(e => e.Texto)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdBessNavigation).WithMany(p => p.BessAlerta)
                .HasForeignKey(d => d.IdBess)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BessAlert__IdBES__76EBA2E9");
        });

        modelBuilder.Entity<CatalogoMaestro>(entity =>
        {
            entity.HasKey(e => e.IdCatalogo).HasName("PK__Catalogo__FD0AC26C2D21C1D8");

            entity.ToTable("CatalogoMaestro");

            entity.Property(e => e.IdCatalogo).ValueGeneratedNever();
            entity.Property(e => e.InfoAdicional).HasMaxLength(100);
            entity.Property(e => e.Nombre).HasMaxLength(100);
        });

        modelBuilder.Entity<CatalogoOpcione>(entity =>
        {
            entity.HasKey(e => new { e.IdCatalogo, e.IdOpcion }).HasName("PK__Catalogo__69F8FAE9CB0818E0");

            entity.Property(e => e.InfoAdicional).HasMaxLength(100);
            entity.Property(e => e.NombreOpcion).HasMaxLength(100);

            entity.HasOne(d => d.IdCatalogoNavigation).WithMany(p => p.CatalogoOpciones)
                .HasForeignKey(d => d.IdCatalogo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CatalogoO__IdCat__778AC167");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__Cliente__D59466429BC3BA9E");

            entity.ToTable("Cliente");

            entity.Property(e => e.IdCliente).ValueGeneratedNever();
            entity.Property(e => e.Contacto)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Rfc)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RFC");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DatosInversoresAjustado>(entity =>
        {
            entity.HasKey(e => e.IdAjuste).HasName("PK__DatosInv__138C2758DCAC7C2F");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.IdUsuarioModificacion).HasMaxLength(450);
            entity.Property(e => e.IdentificadorInversor)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ValorNuevo).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.ValorOriginal).HasColumnType("decimal(18, 6)");

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.DatosInversoresAjustados)
                .HasForeignKey(d => d.IdInstalacion)
                .HasConstraintName("FK__DatosInve__IdIns__00DF2177");

            entity.HasOne(d => d.IdUsuarioModificacionNavigation).WithMany(p => p.DatosInversoresAjustados)
                .HasForeignKey(d => d.IdUsuarioModificacion)
                .HasConstraintName("FK__DatosInve__IdUsu__01D345B0");
        });

        modelBuilder.Entity<DiasFestivo>(entity =>
        {
            entity.HasKey(e => e.IdDiaFestivo).HasName("PK__DiasFest__9A4318846D86AFB5");
        });

        modelBuilder.Entity<DobleVerificacion>(entity =>
        {
            entity.HasKey(e => e.IdVerificacion).HasName("PK__DobleVer__FB60903415F780BC");

            entity.ToTable("DobleVerificacion");

            entity.Property(e => e.CodigoVerificacion)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Expiracion).HasColumnType("datetime");
            entity.Property(e => e.FechaSolicitud).HasColumnType("datetime");

            entity.HasOne(d => d.IdUsuarioRelacionadoNavigation).WithMany(p => p.DobleVerificacions)
                .HasForeignKey(d => d.IdUsuarioRelacionado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DobleVeri__IdUsu__55F4C372");
        });

        modelBuilder.Entity<Documento>(entity =>
        {
            entity.HasKey(e => e.IdDocumento).HasName("PK__Document__E520734726C44ACC");

            entity.ToTable("Documento");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.NombreDocumento)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RutaRelativa)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TipoArchivo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.Documentos)
                .HasForeignKey(d => d.IdInstalacion)
                .HasConstraintName("FK__Documento__IdIns__467D75B8");
        });

        modelBuilder.Entity<Grupo>(entity =>
        {
            entity.HasKey(e => e.IdGrupo).HasName("PK__Grupo__303F6FD9CE05C70C");

            entity.ToTable("Grupo");

            entity.Property(e => e.IdGrupo).ValueGeneratedNever();
            entity.Property(e => e.Nombre).HasMaxLength(50);
        });

        modelBuilder.Entity<InstalacionApigeneracionMensual>(entity =>
        {
            entity.HasKey(e => new { e.IdInstalacion, e.Mes, e.Anno }).HasName("PK__Instalac__92DA0D963B68EA30");

            entity.ToTable("InstalacionAPIGeneracionMensual");

            entity.Property(e => e.GeneracionGarantizada).HasColumnType("decimal(18, 3)");

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.InstalacionApigeneracionMensuals)
                .HasForeignKey(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instalaci__IdIns__29AC2CE0");
        });

        modelBuilder.Entity<Instalacione>(entity =>
        {
            entity.HasKey(e => e.IdInstalacion).HasName("PK__Instalac__03A6C039970B16BE");

            entity.Property(e => e.IdInstalacion).ValueGeneratedNever();
            entity.Property(e => e.CodigoProyecto)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactoEmail)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ContactoNombre)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ContactoTelefono)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Estado).HasMaxLength(50);
            entity.Property(e => e.FechaUltimaActualizacionDaemonApi)
                .HasColumnType("datetime")
                .HasColumnName("FechaUltimaActualizacionDaemonAPI");
            entity.Property(e => e.IdInstalacionApi)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IdInstalacionAPI");
            entity.Property(e => e.Latitud)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Longitud)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Nombre).HasMaxLength(200);
            entity.Property(e => e.PorcentajeDesgastePaneles).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.PotenciaInstalada).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Rpu)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RPU");
            entity.Property(e => e.Ubicacion).HasMaxLength(500);

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Instalaciones)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instalaci__IdCli__0F624AF8");

            entity.HasOne(d => d.IdGrupoNavigation).WithMany(p => p.Instalaciones)
                .HasForeignKey(d => d.IdGrupo)
                .HasConstraintName("FK__Instalaci__IdGru__2739D489");
        });

        modelBuilder.Entity<Inversor>(entity =>
        {
            entity.HasKey(e => e.IdInversor).HasName("PK__Inversor__F91756CCE6089A9D");

            entity.ToTable("Inversor");

            entity.Property(e => e.DegradacionAnual).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Modelo)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.NumeroSerie)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.NumeroSerieReemplazo)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Potencia).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.ProveedorIntermediario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProveedorIntermediarioRfc)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("ProveedorIntermediarioRFC");
            entity.Property(e => e.ProveedorSuministrador)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProveedorSuministradorRfc)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("ProveedorSuministradorRFC");

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.Inversors)
                .HasForeignKey(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inversor__IdInst__6D9742D9");
        });

        modelBuilder.Entity<InversorApiencabezado>(entity =>
        {
            entity.HasKey(e => e.IdInversorApi).HasName("PK__Inversor__7AB25E4E4704AEAE");

            entity.ToTable("InversorAPIEncabezado");

            entity.Property(e => e.IdInversorApi).HasColumnName("IdInversorAPI");
            entity.Property(e => e.FechaUltimaActualizacion).HasColumnType("datetime");
            entity.Property(e => e.IdApi)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IdAPI");
            entity.Property(e => e.NumeroSerie)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.InversorApiencabezados)
                .HasForeignKey(d => d.IdInstalacion)
                .HasConstraintName("FK__InversorA__IdIns__2116E6DF");

            entity.HasOne(d => d.IdInversorNavigation).WithMany(p => p.InversorApiencabezados)
                .HasForeignKey(d => d.IdInversor)
                .HasConstraintName("FK__InversorA__IdInv__220B0B18");
        });

        modelBuilder.Entity<InversorApigeneracion>(entity =>
        {
            entity.HasKey(e => new { e.IdInversorApi, e.IdConsecutivo }).HasName("PK__Inversor__41F3B576EBCA5482");

            entity.ToTable("InversorAPIGeneracion");

            entity.Property(e => e.IdInversorApi).HasColumnName("IdInversorAPI");
            entity.Property(e => e.FechaUltimaActualizacion).HasColumnType("datetime");
            entity.Property(e => e.FechaValor).HasColumnType("datetime");
            entity.Property(e => e.Valor).HasColumnType("decimal(18, 3)");

            entity.HasOne(d => d.IdInversorApiNavigation).WithMany(p => p.InversorApigeneracions)
                .HasForeignKey(d => d.IdInversorApi)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__InversorA__IdInv__24E777C3");
        });

        modelBuilder.Entity<Panele>(entity =>
        {
            entity.HasKey(e => e.IdPanel).HasName("PK__Paneles__1EA4C5E7DE4165A2");

            entity.Property(e => e.DegradacionAnual).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Modelo)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.NumeroSerie)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.NumeroSerieReemplazo)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Potencia).HasColumnType("decimal(18, 6)");
            entity.Property(e => e.ProveedorIntermediario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProveedorIntermediarioRfc)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("ProveedorIntermediarioRFC");
            entity.Property(e => e.ProveedorSuministrador)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProveedorSuministradorRfc)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("ProveedorSuministradorRFC");

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.Paneles)
                .HasForeignKey(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Paneles__IdInsta__7073AF84");
        });

        modelBuilder.Entity<ParametrosBess>(entity =>
        {
            entity.HasKey(e => e.IdParametro).HasName("PK__Parametr__37B016F4699C04B5");

            entity.ToTable("ParametrosBess");

            entity.Property(e => e.IdParametro).ValueGeneratedNever();
            entity.Property(e => e.Medicion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Observaciones)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.SoloLectura).HasDefaultValue(true);
            entity.Property(e => e.Unidad)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ParametrosSistema>(entity =>
        {
            entity.HasKey(e => e.IdParametro).HasName("PK__Parametr__37B016F45C6A776E");

            entity.ToTable("ParametrosSistema");

            entity.HasIndex(e => e.NombreParametro, "UQ__Parametr__17592176F39971BA").IsUnique();

            entity.Property(e => e.IdParametro).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.NombreParametro)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TipoDato)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Valor)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Plataforma>(entity =>
        {
            entity.HasKey(e => e.IdPlataforma).HasName("PK__Platafor__8B82837FC0C6B732");

            entity.ToTable("Plataforma");

            entity.Property(e => e.IdPlataforma).ValueGeneratedNever();
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RecibosMensuale>(entity =>
        {
            entity.HasKey(e => e.IdRecibo).HasName("PK__RecibosM__2FEC473110CB8EEB");

            entity.Property(e => e.KWbase)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("kWBase");
            entity.Property(e => e.KWhBase)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("kWhBase");
            entity.Property(e => e.KWhIntermedia)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("kWhIntermedia");
            entity.Property(e => e.KWhPunta)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("kWhPunta");
            entity.Property(e => e.KWintermedia)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("kWIntermedia");
            entity.Property(e => e.KWpunta)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("kWPunta");
            entity.Property(e => e.Pago).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.ReactivosKvArh).HasColumnType("decimal(8, 2)");

            entity.HasOne(d => d.IdDocumentoNavigation).WithMany(p => p.RecibosMensuales)
                .HasForeignKey(d => d.IdDocumento)
                .HasConstraintName("FK__RecibosMe__IdDoc__0C1BC9F9");

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.RecibosMensuales)
                .HasForeignKey(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RecibosMe__IdIns__0B27A5C0");
        });

        modelBuilder.Entity<ReporteAutomaticoConfig>(entity =>
        {
            entity.HasKey(e => e.IdInstalacion).HasName("PK__ReporteA__03A6C039E789F307");

            entity.ToTable("ReporteAutomaticoConfig");

            entity.Property(e => e.IdInstalacion).ValueGeneratedNever();
            entity.Property(e => e.FpDefault).HasColumnType("decimal(9, 8)");
            entity.Property(e => e.NombreEnRecibo)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.PorcentajeDap)
                .HasColumnType("decimal(9, 8)")
                .HasColumnName("PorcentajeDAP");
            entity.Property(e => e.UmbralFp)
                .HasColumnType("decimal(3, 2)")
                .HasColumnName("UmbralFP");

            entity.HasOne(d => d.IdInstalacionNavigation).WithOne(p => p.ReporteAutomaticoConfig)
                .HasForeignKey<ReporteAutomaticoConfig>(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReporteAu__IdIns__58671BC9");
        });

        modelBuilder.Entity<ReportesMensuale>(entity =>
        {
            entity.HasKey(e => e.IdReporte).HasName("PK__Reportes__F9561136EA7E3552");

            entity.Property(e => e.AhorroAcumulado).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AhorroAmbiental).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ConsumoCfe)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("ConsumoCFE");
            entity.Property(e => e.PanelesGeneracion).HasColumnType("decimal(12, 3)");

            entity.HasOne(d => d.IdDocumentoNavigation).WithMany(p => p.ReportesMensuales)
                .HasForeignKey(d => d.IdDocumento)
                .HasConstraintName("FK__ReportesM__IdDoc__084B3915");

            entity.HasOne(d => d.IdInstalacionNavigation).WithMany(p => p.ReportesMensuales)
                .HasForeignKey(d => d.IdInstalacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ReportesM__IdIns__075714DC");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.IdRol).HasName("PK__Roles__2A49584CF479F659");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TagsBess>(entity =>
        {
            entity.HasKey(e => e.IdTag).HasName("PK__TagsBess__2BC60B0B0C1D4362");

            entity.ToTable("TagsBess");

            entity.Property(e => e.MensajeEstatus)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.NombreAmostrar)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("")
                .HasColumnName("NombreAMostrar");
            entity.Property(e => e.Tag)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdBessNavigation).WithMany(p => p.TagsBesses)
                .HasForeignKey(d => d.IdBess)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TagsBess__IdBess__7226EDCC");

            entity.HasOne(d => d.IdParametroNavigation).WithMany(p => p.TagsBesses)
                .HasForeignKey(d => d.IdParametro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TagsBess__IdPara__731B1205");
        });

        modelBuilder.Entity<TarifasDivisione>(entity =>
        {
            entity.HasKey(e => new { e.IdTarifa, e.IdDivision, e.Anno, e.Mes }).HasName("PK__TarifasD__15AA3EAB2378B198");

            entity.Property(e => e.ValorCapacidad).HasColumnType("decimal(8, 4)");
            entity.Property(e => e.ValorDistribucion).HasColumnType("decimal(8, 4)");
            entity.Property(e => e.ValorEnergiaBase).HasColumnType("decimal(8, 4)");
            entity.Property(e => e.ValorEnergiaIntermedia).HasColumnType("decimal(8, 4)");
            entity.Property(e => e.ValorEnergiaPunta).HasColumnType("decimal(8, 4)");
            entity.Property(e => e.ValorEnergiaSemipunta).HasColumnType("decimal(8, 4)");
            entity.Property(e => e.ValorOpCenace)
                .HasColumnType("decimal(8, 4)")
                .HasColumnName("ValorOpCENACE");
            entity.Property(e => e.ValorOpSsb)
                .HasColumnType("decimal(8, 4)")
                .HasColumnName("ValorOpSSB");
            entity.Property(e => e.ValorServiciosNoMem)
                .HasColumnType("decimal(8, 4)")
                .HasColumnName("ValorServiciosNoMEM");
            entity.Property(e => e.ValorTransmision).HasColumnType("decimal(8, 4)");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Users__5B65BF97201325F3");

            entity.Property(e => e.UsApellidos).HasMaxLength(50);
            entity.Property(e => e.UsCntrsn)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.UsCorreo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UsFechaAlta).HasColumnType("datetime");
            entity.Property(e => e.UsNombre).HasMaxLength(50);

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.IdRol)
                .HasConstraintName("FK__Users__IdRol__7C4F7684");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}