// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Skysense_persistencia.Entidades;

namespace Skysense_persistencia.Entidades
{
    public partial class SkysenseDevContext
    {

        [DbFunction("fObtenGeneracionDiariaInversor", "dbo")]
        public IQueryable<fObtenGeneracionDiariaInversorResult> fObtenGeneracionDiariaInversor(int? idInstalacion, short? iAnio, byte? iMes)
        {
            return FromExpression(() => fObtenGeneracionDiariaInversor(idInstalacion, iAnio, iMes));
        }

        [DbFunction("fObtenGeneracionMensual", "dbo")]
        public IQueryable<fObtenGeneracionMensualResult> fObtenGeneracionMensual(int? idInstalacion, short? iAnio)
        {
            return FromExpression(() => fObtenGeneracionMensual(idInstalacion, iAnio));
        }

        [DbFunction("fObtenKPIInstalacionesAnualMensual", "dbo")]
        public IQueryable<fObtenKPIInstalacionesAnualMensualResult> fObtenKPIInstalacionesAnualMensual(short? iAnno, byte? iMes, bool? bAnnoGarantia0Real1)
        {
            return FromExpression(() => fObtenKPIInstalacionesAnualMensual(iAnno, iMes, bAnnoGarantia0Real1));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fObtenGeneracionDiariaInversorResult>().HasNoKey();
            modelBuilder.Entity<fObtenGeneracionMensualResult>().HasNoKey();
            modelBuilder.Entity<fObtenKPIInstalacionesAnualMensualResult>().HasNoKey();
        }
    }
}
