// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class TagsBess
{
    public int IdTag { get; set; }

    public int IdBess { get; set; }

    public short IdParametro { get; set; }

    public string Tag { get; set; }

    public bool Monitorear { get; set; }

    public byte? Estatus { get; set; }

    public DateTime? UltimaActualizacionEstatus { get; set; }

    public string MensajeEstatus { get; set; }

    public bool Activo { get; set; }

    public string NombreAmostrar { get; set; }

    public byte? IdGrafica { get; set; }

    public virtual Bess IdBessNavigation { get; set; }

    public virtual ParametrosBess IdParametroNavigation { get; set; }
}