// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.Entidades;

public partial class User
{
    public int IdUsuario { get; set; }

    public byte UsEstado { get; set; }

    public string UsNombre { get; set; }

    public string UsApellidos { get; set; }

    public string UsCorreo { get; set; }

    public string UsCntrsn { get; set; }

    public DateTime UsFechaAlta { get; set; }

    public byte? IdRol { get; set; }

    public bool? UsCambiaCntrsn { get; set; }

    public virtual ICollection<DobleVerificacion> DobleVerificacions { get; set; } = new List<DobleVerificacion>();

    public virtual Role IdRolNavigation { get; set; }
}