// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.EntidadesBESS;

public partial class Bess
{
    public int IdBess { get; set; }

    public int IdInstalacion { get; set; }

    public string UrlEms { get; set; }

    public bool? SiMedir { get; set; }

    public virtual ICollection<Modulo> Modulo { get; set; } = new List<Modulo>();

    public virtual ICollection<TagsBess> TagsBess { get; set; } = new List<TagsBess>();
}