// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.EntidadesBESS;

public partial class Modulo
{
    public int IdModulo { get; set; }

    public int IdBess { get; set; }

    public virtual Bess IdBessNavigation { get; set; }
}