// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.EntidadesBESS;

public partial class ParametrosBaterias
{
    public int IdParametro { get; set; }

    public string Medicion { get; set; }

    public string Observaciones { get; set; }

    public string Unidad { get; set; }

    public virtual ICollection<TagsBess> TagsBess { get; set; } = new List<TagsBess>();
}