// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Skysense_persistencia.EntidadesBESS;

public partial class SkysenseBateriasContext : DbContext
{
    public SkysenseBateriasContext(DbContextOptions<SkysenseBateriasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bess> Bess { get; set; }

    public virtual DbSet<Modulo> Modulo { get; set; }

    public virtual DbSet<ParametrosBaterias> ParametrosBaterias { get; set; }

    public virtual DbSet<TagsBess> TagsBess { get; set; }

    public virtual DbSet<TagsMediciones> TagsMediciones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bess>(entity =>
        {
            entity.HasKey(e => e.IdBess).HasName("PK__BESS__382B18DC1C14371B");

            entity.ToTable("BESS");

            entity.Property(e => e.IdBess).HasColumnName("IdBESS");
            entity.Property(e => e.UrlEms)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Modulo>(entity =>
        {
            entity.HasKey(e => e.IdModulo).HasName("PK__Modulo__D9F15315923CC808");

            entity.Property(e => e.IdBess).HasColumnName("IdBESS");

            entity.HasOne(d => d.IdBessNavigation).WithMany(p => p.Modulo)
                .HasForeignKey(d => d.IdBess)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Modulo__IdBESS__3C69FB99");
        });

        modelBuilder.Entity<ParametrosBaterias>(entity =>
        {
            entity.HasKey(e => e.IdParametro).HasName("PK__Parametr__37B016F4E7EF2CBD");

            entity.Property(e => e.IdParametro).ValueGeneratedNever();
            entity.Property(e => e.Medicion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Observaciones)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Unidad)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TagsBess>(entity =>
        {
            entity.HasKey(e => e.IdTag).HasName("PK__TagsBESS__2BC60B0BF352BC01");

            entity.ToTable("TagsBESS");

            entity.Property(e => e.Etiqueta)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdBessNavigation).WithMany(p => p.TagsBess)
                .HasForeignKey(d => d.IdBess)
                .HasConstraintName("FK__TagsBESS__IdBess__66603565");

            entity.HasOne(d => d.IdParametroNavigation).WithMany(p => p.TagsBess)
                .HasForeignKey(d => d.IdParametro)
                .HasConstraintName("FK__TagsBESS__IdPara__656C112C");
        });

        modelBuilder.Entity<TagsMediciones>(entity =>
        {
            entity.HasKey(e => e.IdMedicion).HasName("PK__TagsMedi__0DAF13BAF722EF16");

            entity.HasOne(d => d.IdTagNavigation).WithMany(p => p.TagsMediciones)
                .HasForeignKey(d => d.IdTag)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TagsMedic__IdTag__693CA210");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}