// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.EntidadesBESS;

public partial class TagsMediciones
{
    public int IdMedicion { get; set; }

    public int IdTag { get; set; }

    public DateTime Fecha { get; set; }

    public short Medicion { get; set; }

    public virtual TagsBess IdTagNavigation { get; set; }
}