// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Skysense_persistencia.EntidadesBESS;

public partial class TagsBess
{
    public int IdTag { get; set; }

    public int? IdParametro { get; set; }

    public int? IdBess { get; set; }

    public string Etiqueta { get; set; }

    public bool? SiMedir { get; set; }

    public virtual Bess IdBessNavigation { get; set; }

    public virtual ParametrosBaterias IdParametroNavigation { get; set; }

    public virtual ICollection<TagsMediciones> TagsMediciones { get; set; } = new List<TagsMediciones>();
}