// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Skysense_models.DB.FunctionReturns
{
    public partial class CfObtenGeneracionMensualResult
    {
        public int? Mes { get; set; }
        public decimal? GeneracionMes { get; set; }
    }
}
